apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: telemetry-serverless
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"   # optional: keep one pod warm
        autoscaling.knative.dev/maxScale: "5"   # optional: burst limit
    spec:
      containers:
        - image: shemathomas/jsontelemetry-infer:latest
          ports:
            - containerPort: 8000
          env:
            - name: MODE
              value: "burst"
            - name: SUBMODE
              value: "st"

