# Makefile

.PHONY: clean

clean:
	@echo "[INFO] Cleaning strace/, data/, log/, perf/ and result* files..."
	@rm -rf data/* strace/* log/* perf/* result* serverless_data/* 
	@echo "[INFO] Cleanup complete."

