apiVersion: v1
kind: Service
metadata:
  name: redis-external-server
  namespace: default
spec:
  type: NodePort
  selector:
    app: redis-server
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30079    # accessible externally

