#!/usr/bin/env bash
# =============================================================================
# run_container.sh — DeepStream benchmarking, Docker container execution
# Lives at: perception_infer_pipeline_container_node/
#
# Usage:  ./run_container.sh <image_directory> [IMAGE_TAG]
#
# METRIC COLLECTION NOTES (important for cross-mode comparison):
#
#   timing/RSS/CPU : /usr/bin/time -v wraps the docker client process on the
#                    host. It captures the docker CLI RSS (~30MB), NOT DeepStream
#                    RSS inside the container. This is a known container
#                    measurement boundary — noted in CSV as host-side.
#                    For true in-container RSS use tegrastats (bench_logs/).
#
#   latency        : wall-clock from docker run start to exit — includes
#                    container startup overhead (~2-5s). Comparable across
#                    container runs but ~2-5s higher than native equivalent.
#
#   perf stat IPC  : NOW in-container — perf stat runs inside a privileged
#                    container wrapping deepstream-app directly. Comparable
#                    to native perf stat output.
#                    Validated on Jetson Nano 5.15.148-tegra:
#                      host perf 5.15.189 (generic) volume-mounted into container
#                      --privileged + --pid=host + seccomp=unconfined → real PMU
#                      all counters confirmed non-<not supported>
#
#   nsys           : NOW in-container — nsys runs inside a privileged container
#                    wrapping deepstream-app directly. Full CUDA API, GPU kernels,
#                    NVTX, and OS runtime — fully comparable to native.
#                    Validated in trial_nsys_container.sh:
#                      host nsight-systems volume-mounted into container
#                      --privileged + --pid=host + seccomp=unconfined → real CUDA trace
#                      all sections confirmed non-SKIPPED
#
#   ncu            : runs inside privileged container — kernel metrics are
#                    identical to native ncu output. Primary GPU comparison tool.
#
#   tegrastats     : PID-attaches to the deepstream-app process inside the
#                    container. Provides in-container CPU/GPU/memory comparable
#                    to native tegrastats. Primary host-resource comparison tool.
#
# TRT ENGINE NOTE:
#   Container image ships TRT 10.3.0.26; host has TRT 10.3.0.30.
#   Engines are not cross-compatible (patch version mismatch).
#   Container uses: models/yolov4-tiny-decoded.onnx_b1_gpu0_fp16.engine
#   Native uses   : models/yolov4-tiny-decoded_b1_gpu0_fp16.engine
#   The ~4.7% instruction count difference between modes is from different
#   TRT tactic selection, not Docker overhead. Docker overhead = ~0%.
# =============================================================================

set -euo pipefail

export ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export MODE="container"

DOCKER_IMG="${2:-nvcr.io/nvidia/deepstream-l4t:7.1-samples-multiarch}"

export DS_CONFIG_SRC="${ROOT}/configs/av_app.txt"
export VIDEO_PORT=8080
export VIDEO_HOST_IP="127.0.0.1"

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <image_directory> [IMAGE_TAG]"
    exit 1
fi

export IMG_DIR="$1"

# ---------------------------------------------------------------------------
# Host perf binary — volume-mounted into privileged container for sub-pass B.
# Image has no perf installed. Host generic binary (5.15.189) works against
# Tegra kernel (5.15.148-tegra) — validated empirically.
# ---------------------------------------------------------------------------
HOST_PERF="$(readlink -f "$(which perf)")"

# ---------------------------------------------------------------------------
# perf_event_paranoid
# ---------------------------------------------------------------------------
echo "[SETUP] Setting kernel.perf_event_paranoid=0 ..."
echo 0 | sudo tee /proc/sys/kernel/perf_event_paranoid >/dev/null

# ---------------------------------------------------------------------------
# Suppress ConnectionResetError noise from the Python HTTP server.
# ---------------------------------------------------------------------------
export _HTTP_SERVER_SUPPRESS_ERRORS=1

# ---------------------------------------------------------------------------
# Per-pass wrapper scripts
# bench_common.sh calls: $DS_BIN -c $DS_CONFIG  (host absolute path)
# Wrappers translate DS_CONFIG host path → /workspace/configs/<filename>
# ---------------------------------------------------------------------------
_mk_wrapper() {
    local wpath="$1"
    cat > "$wpath" << WRAPPER
#!/usr/bin/env bash
# Auto-generated by run_container.sh — do not edit
set +e
CONFIG_PATH="\$2"
CONTAINER_CFG="/workspace/configs/\$(basename "\$CONFIG_PATH")"
exec docker run --rm \
    --runtime nvidia \
    --network host \
    --log-driver=none \
    -v "${ROOT}":/workspace \
    -w /workspace \
    -e LD_LIBRARY_PATH="/opt/nvidia/deepstream/deepstream-7.1/lib:/opt/nvidia/deepstream/deepstream-7.1/lib/gst-plugins" \
    -e GST_PLUGIN_PATH="/opt/nvidia/deepstream/deepstream-7.1/lib/gst-plugins" \
    "${DOCKER_IMG}" \
    deepstream-app -c "\$CONTAINER_CFG"
WRAPPER
    chmod +x "$wpath"
}

_TIMING_WRAPPER="${ROOT}/.ds_wrapper_timing.sh"
_NSYS_WRAPPER="${ROOT}/.ds_wrapper_nsys.sh"
_PERF_WRAPPER="${ROOT}/.ds_wrapper_perf.sh"
_mk_wrapper "$_TIMING_WRAPPER"
_mk_wrapper "$_NSYS_WRAPPER"
_mk_wrapper "$_PERF_WRAPPER"

export DS_BIN="$_TIMING_WRAPPER"

# ---------------------------------------------------------------------------
# Source shared library
# ---------------------------------------------------------------------------
# shellcheck source=bench_scripts/bench_common.sh
source "${ROOT}/bench_scripts/bench_common.sh"

# ---------------------------------------------------------------------------
# Override bench_run_timing
#
# Sub-pass A: unchanged — /usr/bin/time -v wraps docker client (host-side RSS/CPU)
#             + baseline PID-attach profilers
#
# Sub-pass B: FIXED — perf stat runs INSIDE privileged container wrapping
#             deepstream-app directly, giving real in-process PMU counters.
#
#             OLD (broken): host perf stat "$DS_BIN" -c "$DS_CONFIG"
#               → wraps the docker client wrapper script
#               → sees ~102M instructions (CLI overhead only, not DS)
#
#             NEW (fixed): docker run --privileged ... perf stat deepstream-app
#               → perf runs inside container namespace
#               → wraps deepstream-app directly
#               → sees real DS instructions (~4B, comparable to native)
# ---------------------------------------------------------------------------
bench_run_timing() {
    local TIME_LOG="${PERF_DIR}/time_${_RUN_ID}.txt"
    local LOGFILE="${LOG_DIR}/run_${_RUN_ID}_timing.log"
    PERF_STAT="${PERF_DIR}/perf_stat_${_RUN_ID}.csv"
    local CONTAINER_CFG="/workspace/configs/$(basename "$DS_CONFIG")"

    export DS_BIN="$_TIMING_WRAPPER"

    # ------------------------------------------------------------------
    # Sub-pass A: /usr/bin/time -v + baseline PID-attach  (unchanged)
    # ------------------------------------------------------------------
    echo ""
    echo "[PASS: timing / sub-pass A] /usr/bin/time -v — single DS run..."
    echo "[NOTE] RSS and CPU% reflect the docker client process (host-side)."
    echo "       In-container memory → tegrastats in bench_logs/"
    echo "       In-container GPU    → nsys / ncu passes"

    _START_NS=$(date +%s%N)

    local _DS_RC=0
    {
        /usr/bin/time -v \
            bash -c 'exec "$0" -c "$1" >"$2" 2>&1' \
            "$DS_BIN" "$DS_CONFIG" "$LOGFILE" \
            2>"$TIME_LOG" &
        local _TIME_PID=$!

        sleep 8
        echo "[PASS: baseline] Launching PID-attach profilers (DS should be running)..."
        local _DS_CONTAINER_PID
        _DS_CONTAINER_PID=$(pgrep -f "deepstream-app" | head -1 || true)
        if [[ -n "$_DS_CONTAINER_PID" ]]; then
            echo "[PASS: baseline] Attaching to deepstream-app PID: $_DS_CONTAINER_PID"
        else
            echo "[PASS: baseline] deepstream-app PID not found yet — baseline will retry"
        fi
        MODE="$MODE" TAG="$_RUN_ID" DUR_TOTAL=120 \
            bash "${ROOT}/bench_scripts/run_baseline.sh" \
            >> "${LOG_DIR}/run_${_RUN_ID}_baseline.log" 2>&1 &
        _BASELINE_PID=$!

        wait "$_TIME_PID" || _DS_RC=$?
    }

    _END_NS=$(date +%s%N)

    echo "[INFO] --- DS output: first 20 lines ---"
    head -20 "$LOGFILE" 2>/dev/null || echo "(log empty)"
    echo "[INFO] --- DS output: last 20 lines ---"
    tail -20 "$LOGFILE" 2>/dev/null || true
    echo "[INFO] --- end DS output ---"

    if (( _DS_RC != 0 )); then
        echo "[WARN] docker run / deepstream-app exited code=${_DS_RC}"
        echo "[WARN]   code=1   → normal EOS pipeline drain"
        echo "[WARN]   code=125 → docker run failed (check image/runtime)"
        echo "[WARN]   code=255 → DS fatal error inside container"
    fi

    # ------------------------------------------------------------------
    # Sub-pass B: perf stat INSIDE privileged container  (fixed)
    #
    # Flags:
    #   --privileged          removes cgroup perf_event filter
    #   --pid=host            perf sees host PID namespace (required for PMU)
    #   --cap-add SYS_ADMIN   perf_event_open syscall access
    #   --cap-add SYS_PTRACE  perf attach
    #   --security-opt seccomp=unconfined  removes seccomp perf_event_open block
    #   --security-opt apparmor=unconfined removes apparmor PMU block
    #   -v HOST_PERF:/usr/local/bin/perf   inject host perf (image has none)
    #   -r 3                  repeat 3 times, report average + stddev (same as native)
    # ------------------------------------------------------------------
    echo ""
    echo "[PASS: timing / sub-pass B] perf stat inside privileged container — 3 runs averaged..."
    echo "[NOTE] perf wraps deepstream-app directly — comparable to native perf stat."

    docker run --rm \
        --runtime nvidia \
        --privileged \
        --pid=host \
        --network host \
        --cap-add SYS_ADMIN \
        --cap-add SYS_PTRACE \
        --security-opt seccomp=unconfined \
        --security-opt apparmor=unconfined \
        --log-driver=none \
        -v "${ROOT}":/workspace \
        -v "${HOST_PERF}":/usr/local/bin/perf:ro \
        -w /workspace \
        -e LD_LIBRARY_PATH="/opt/nvidia/deepstream/deepstream-7.1/lib:/opt/nvidia/deepstream/deepstream-7.1/lib/gst-plugins" \
        -e GST_PLUGIN_PATH="/opt/nvidia/deepstream/deepstream-7.1/lib/gst-plugins" \
        "${DOCKER_IMG}" \
        bash -c "
            perf stat -x, -r 3 \
                -o /workspace/perf/perf_stat_${_RUN_ID}.csv \
                -e task-clock,context-switches,cpu-migrations,page-faults,\
cycles,instructions,branch-misses,cache-references,cache-misses \
                deepstream-app -c \"${CONTAINER_CFG}\"
        " >> "$LOGFILE" 2>&1 \
    || echo "[WARN] perf stat container run exited non-zero — check $LOGFILE"

    echo "[PASS: timing] Waiting for baseline profilers to finish..."
    wait "$_BASELINE_PID" 2>/dev/null || true

    # ------------------------------------------------------------------
    # Extract metrics — identical awk to bench_common.sh bench_run_timing
    # ------------------------------------------------------------------
    _LAT_S=$(awk -v s="$_START_NS" -v e="$_END_NS" \
        'BEGIN {printf "%.3f", (e - s) / 1e9}')

    _MEM_KB=$(grep "Maximum resident set size" "$TIME_LOG" | awk '{print $NF}')
    _MEM_MB=$(awk "BEGIN {printf \"%.2f\", ${_MEM_KB:-0}/1024}")

    _CPU_PCT=$(grep "Percent of CPU this job got" "$TIME_LOG" | \
        awk '{print $NF}' | tr -d '%')

    _IPC=$(awk -F, '
        /instructions/ && $7 ~ /^[0-9]/ { printf "%.3f", $7+0; exit }
    ' "$PERF_STAT")
    _IPC="${_IPC:-N/A}"

    _CACHE_MISS_PCT=$(awk -F, '
        /cache-misses/ && $7 ~ /^[0-9]/ { printf "%.2f", $7+0; exit }
    ' "$PERF_STAT")
    _CACHE_MISS_PCT="${_CACHE_MISS_PCT:-N/A}"

    _BRANCH_MISS_PCT=$(awk -F, '
        /branch-misses/ && $1 ~ /^[0-9]/ { print $1+0; exit }
    ' "$PERF_STAT")
    _BRANCH_MISS_PCT="${_BRANCH_MISS_PCT:-N/A}"

    echo "[METRICS] Latency (wall, incl. container start) : ${_LAT_S}s"
    echo "[METRICS] Memory RSS (host docker client)       : ${_MEM_MB} MB"
    echo "[METRICS] CPU util  (host docker client)        : ${_CPU_PCT}%"
    echo "[METRICS] IPC       (in-container DS process)   : ${_IPC}"
    echo "[METRICS] Cache miss (in-container DS process)  : ${_CACHE_MISS_PCT}%"
    echo "[METRICS] Branch misses (abs, in-container)     : ${_BRANCH_MISS_PCT}"
    echo "[NOTE] IPC/instructions/cache now reflect DS internals — comparable to native"
    echo "[NOTE] mem_mb/cpu_pct = docker client (host-side); use tegrastats for DS values"

    bench_append_csv "timing" \
        "$_LAT_S" "$_MEM_MB" "$_CPU_PCT" \
        "$_IPC" "$_CACHE_MISS_PCT" "$_BRANCH_MISS_PCT" \
        "N/A" "$PERF_STAT" "N/A" "N/A"
}

# ---------------------------------------------------------------------------
# Override bench_run_nsys
#
# Approach: volume-mount host nsight-systems into the container and run
# nsys inside the container directly wrapping deepstream-app.
#
# OLD (broken): host nsys wraps docker run wrapper script
#   → nsys profiles the bash wrapper + docker client on the host
#   → CUDA context lives in container namespace — not visible to host nsys
#   → result: no CUDA trace, no NVTX, no GPU kernels (all SKIPPED)
#
# NEW (fixed): nsys runs INSIDE privileged container wrapping deepstream-app
#   → validated in trial_nsys_container.sh
#   → mirrors bench_run_ncu pattern exactly
#   → full CUDA API, GPU kernels, NVTX, memory ops — comparable to native
#
# Key flags (same as bench_run_ncu):
#   --privileged + --pid=host        CUDA driver access across namespaces
#   --cap-add SYS_ADMIN/SYS_PTRACE  perf_event_open + attach
#   --security-opt seccomp/apparmor=unconfined  remove PMU blocks
#   -v NSYS_INSTALL:NSYS_INSTALL:ro  inject host nsys (image has none)
#   --output to /workspace/perf/     lands in host-mounted volume
# ---------------------------------------------------------------------------
bench_run_nsys() {
    local NSYS_OUT="${PERF_DIR}/nsys_${_RUN_ID}"
    local LOGFILE="${LOG_DIR}/run_${_RUN_ID}_nsys.log"
    local NSYS_INSTALL="/opt/nvidia/nsight-systems/2024.5.4"
    local NSYS_BIN="${NSYS_INSTALL}/target-linux-tegra-armv8/nsys"
    local CONTAINER_CFG="/workspace/configs/$(basename "$DS_CONFIG")"

    if [[ ! -f "$NSYS_BIN" ]]; then
        echo "[PASS: nsys] nsys binary not found at $NSYS_BIN — skipping."
        bench_append_csv "nsys" "N/A" "N/A" "N/A" "N/A" "N/A" "N/A" \
            "N/A" "N/A" "N/A" "N/A"
        return 0
    fi

    echo ""
    echo "[PASS: nsys] Nsight Systems — nsys inside privileged container..."
    echo "[PASS: nsys]   nsight-systems : $NSYS_INSTALL (volume-mounted)"
    echo "[PASS: nsys]   trace=cuda,nvtx,osrt  sample=none  (mirrors native)"

    docker run --rm \
        --runtime nvidia \
        --privileged \
        --pid=host \
        --network host \
        --cap-add SYS_ADMIN \
        --cap-add SYS_PTRACE \
        --security-opt seccomp=unconfined \
        --security-opt apparmor=unconfined \
        --log-driver=none \
        -v "${ROOT}":/workspace \
        -v "${NSYS_INSTALL}:${NSYS_INSTALL}:ro" \
        -w /workspace \
        -e LD_LIBRARY_PATH="/opt/nvidia/deepstream/deepstream-7.1/lib:/opt/nvidia/deepstream/deepstream-7.1/lib/gst-plugins" \
        -e GST_PLUGIN_PATH="/opt/nvidia/deepstream/deepstream-7.1/lib/gst-plugins" \
        "${DOCKER_IMG}" \
        bash -c "
            ${NSYS_BIN} profile \
                --trace=cuda,nvtx,osrt \
                --sample=none \
                --output /workspace/perf/nsys_${_RUN_ID} \
                deepstream-app -c \"${CONTAINER_CFG}\"
        " >> "$LOGFILE" 2>&1 \
    || echo "[WARN] nsys exited non-zero — check $LOGFILE"

    local NSYS_FILE="${NSYS_OUT}.nsys-rep"
    [[ -f "$NSYS_FILE" ]] || NSYS_FILE="${NSYS_OUT}.qdrep"
    [[ -f "$NSYS_FILE" ]] && echo "[PASS: nsys] Output: $NSYS_FILE" \
                          || echo "[WARN] nsys output file not found at $NSYS_FILE"

    bench_append_csv "nsys" "N/A" "N/A" "N/A" "N/A" "N/A" "N/A" \
        "$NSYS_FILE" "N/A" "N/A" "N/A"
}

# ---------------------------------------------------------------------------
# Override bench_run_perf_record — identical to original run_container.sh
# ---------------------------------------------------------------------------
bench_run_perf_record() {
    local PERF_RECORD="${PERF_DIR}/perf_record_${_RUN_ID}.data"
    local PERF_REPORT="${PERF_DIR}/perf_report_${_RUN_ID}.txt"
    local LOGFILE="${LOG_DIR}/run_${_RUN_ID}_perf_record.log"

    echo ""
    echo "[PASS: perf_record] perf record — wrapping docker run on host..."
    export DS_BIN="$_PERF_WRAPPER"
    sudo perf record \
        -F 999 -g \
        --call-graph=dwarf \
        -o "$PERF_RECORD" \
        "$_PERF_WRAPPER" -c "$DS_CONFIG" \
        >> "$LOGFILE" 2>&1 \
    || echo "[WARN] perf record exited non-zero"

    sudo perf report \
        --stdio \
        -i "$PERF_RECORD" \
        > "$PERF_REPORT" 2>&1 \
    || echo "[WARN] perf report failed"

    echo "[PASS: perf_record] data → $PERF_RECORD  report → $PERF_REPORT"
    bench_append_csv "perf_record" "N/A" "N/A" "N/A" "N/A" "N/A" "N/A" \
        "N/A" "N/A" "$PERF_RECORD" "N/A"
}

# ---------------------------------------------------------------------------
# Override bench_run_ncu
#
# Approach: volume-mount host nsight-compute into the container and run
# ncu inside the container directly wrapping deepstream-app.
#
# This is the validated working approach (tested manually):
#   - ncu is not installed in the container image
#   - Host ncu wrapping docker run causes segfault (error 139)
#   - Solution: -v /opt/nvidia/nsight-compute/2024.3.1 into container,
#     run ${NCU_INSTALL}/ncu inside container — captures 3986 kernel rows,
#     20 unique inference kernel types
#
# Key flags vs original broken version:
#   --launch-skip 0          (was 200 — massively overshot, missed all kernels)
#   --clock-control base     (new — locks GPU clocks for reproducible metrics)
#   --target-processes application-only (was 'all' — caused segfault)
#   No loop config needed    (DS runs ~14s, enough for 50 kernels)
#   ncu runs INSIDE container (not host ncu wrapping docker)
# ---------------------------------------------------------------------------
bench_run_ncu() {
    local NCU_OUT="${PERF_DIR}/ncu_${_RUN_ID}.csv"
    local LOGFILE="${LOG_DIR}/run_${_RUN_ID}_ncu.log"
    local NCU_INSTALL="/opt/nvidia/nsight-compute/2024.3.1"
    local CONTAINER_CFG="/workspace/configs/$(basename "$DS_CONFIG")"

    if [[ ! -d "$NCU_INSTALL" ]]; then
        echo "[PASS: ncu] nsight-compute not found at $NCU_INSTALL — skipping."
        bench_append_csv "ncu" "N/A" "N/A" "N/A" "N/A" "N/A" "N/A" \
            "N/A" "N/A" "N/A" "N/A"
        return 0
    fi

    echo ""
    echo "[PASS: ncu] Nsight Compute — ncu inside privileged container..."
    echo "[PASS: ncu]   nsight-compute : $NCU_INSTALL (volume-mounted)"
    echo "[PASS: ncu]   launch-skip=0, launch-count=50, set=full, clock-control=base"

    docker run --rm \
        --runtime nvidia \
        --privileged \
        --pid=host \
        --network host \
        --cap-add SYS_ADMIN \
        --cap-add SYS_PTRACE \
        --security-opt seccomp=unconfined \
        --security-opt apparmor=unconfined \
        --log-driver=none \
        -v "${ROOT}":/workspace \
        -v "${NCU_INSTALL}:${NCU_INSTALL}:ro" \
        -w /workspace \
        -e LD_LIBRARY_PATH="/opt/nvidia/deepstream/deepstream-7.1/lib:/opt/nvidia/deepstream/deepstream-7.1/lib/gst-plugins" \
        -e GST_PLUGIN_PATH="/opt/nvidia/deepstream/deepstream-7.1/lib/gst-plugins" \
        "${DOCKER_IMG}" \
        bash -c "
            ${NCU_INSTALL}/ncu \
                --target-processes application-only \
                --launch-skip 0 \
                --launch-count 50 \
                --set full \
                --clock-control base \
                --csv \
                --log-file /workspace/perf/ncu_${_RUN_ID}.csv \
                deepstream-app -c \"${CONTAINER_CFG}\"
        " >> "$LOGFILE" 2>&1 || true

    if [[ -f "$NCU_OUT" ]] && grep -q '"deepstream-app"' "$NCU_OUT" 2>/dev/null; then
        local _KERNEL_COUNT
        _KERNEL_COUNT=$(grep -c '"deepstream-app"' "$NCU_OUT" 2>/dev/null || echo 0)
        echo "[PASS: ncu] Output: $NCU_OUT  (${_KERNEL_COUNT} kernel rows)"
        bench_append_csv "ncu" "N/A" "N/A" "N/A" "N/A" "N/A" "N/A" \
            "N/A" "N/A" "N/A" "$NCU_OUT"
        bench_summarize_ncu "$NCU_OUT"
    else
        echo "[WARN] ncu CSV empty or no kernels captured — check $LOGFILE"
        grep -i 'warn\|error' "$LOGFILE" 2>/dev/null | tail -10 || true
        bench_append_csv "ncu" "N/A" "N/A" "N/A" "N/A" "N/A" "N/A" \
            "N/A" "N/A" "N/A" "N/A"
    fi
}

# ---------------------------------------------------------------------------
# Trap
# ---------------------------------------------------------------------------
_BASELINE_PID=""
trap 'bench_cleanup
      rm -f "$_TIMING_WRAPPER" "$_NSYS_WRAPPER" "$_PERF_WRAPPER"
      [[ -n "$_BASELINE_PID" ]] && kill "$_BASELINE_PID" 2>/dev/null || true' \
    EXIT INT TERM

# ---------------------------------------------------------------------------
# Verify Docker and image
# ---------------------------------------------------------------------------
docker info &>/dev/null || { echo "[ERROR] Docker not running." >&2; exit 1; }
if ! docker image inspect "$DOCKER_IMG" &>/dev/null; then
    echo "[CONTAINER] Image $DOCKER_IMG not found locally — pulling..."
    docker pull "$DOCKER_IMG"
fi

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
bench_init
bench_preflight

bench_start_video
bench_patch_uri "$VIDEO_URL"

echo ""
echo "===== CONTAINER PROFILING PASSES ==================================="
echo "  Image    : $DOCKER_IMG"
echo "  Host IP  : $VIDEO_HOST_IP (--network host)"
echo "  Host perf: $HOST_PERF (volume-mounted into container)"
echo "  timing A : host /usr/bin/time -v wraps docker run  (RSS/CPU host-side)"
echo "  timing B : perf stat INSIDE privileged container   (comparable to native)"
echo "  nsys     : nsys inside privileged container        (GPU trace fully comparable to native)"
echo "  perf_rec : host perf record wraps docker run"
echo "  ncu      : ncu inside privileged container         (direct GPU PMU)"
echo "===================================================================="
echo ""

bench_run_timing
bench_run_nsys
bench_run_perf_record
bench_run_ncu

echo ""
echo "===== CONTAINER BENCHMARK COMPLETE ================================="
echo "  Mode    : $MODE"
echo "  Run ID  : $_RUN_ID"
echo "  Logs    : ${ROOT}/logs/"
echo "  Perf    : ${ROOT}/perf/"
echo "  Baseline: ${ROOT}/bench_logs/"
echo "  CSV     : ${ROOT}/results_unified.csv"
echo ""
echo "  Cross-mode comparison notes:"
echo "    latency_s         : container includes ~2-5s docker startup overhead"
echo "    mem_mb / cpu_pct  : docker client (host-side); use tegrastats for DS values"
echo "    ipc / instructions: in-container DS process — directly comparable to native"
echo "    cache / branch    : in-container DS process — directly comparable to native"
echo "    nsys / ncu        : GPU metrics fully comparable to native"
echo "    tegrastats        : bench_logs/ — primary in-container resource comparison"
echo "    trt engine        : container TRT 10.3.0.26 vs native TRT 10.3.0.30 — ~4.7%"
echo "                        instruction delta is TRT tactic difference, not Docker"
echo "===================================================================="
